### PR TITLE
Athanor server 32

### PR DESCRIPTION
**Pull request by josephharfouch**
Hi Andrew, 

I have implemented this in a similar way to the grammar path. I had more difficulty with trying to do automate the testing with this, which I left some comments about in the code. I also documented the way it is meant to work. Please review and let me know what you think. I will respond to your comments and continue working on this if necessary tomorrow (Monday). Thanks

### CODE REVIEW

**Comment by andrewresearch** [comment]
Hi Joseph, I'm not sure that I follow what you have done here.
All we needed for this issue was to modify the end point such that it retrieves a path parameter.

i.e. when  a request is made to:
```http://athanor.server/v2/analyse/text/rhetorical?grammar=analytic``` then it calls a function in Athanor with the "analytic" option and we load "apply_ana.kif" and call "apply".

A request to:
```http://athanor.server/v2/analyse/text/rhetorical?grammar=reflective``` would call the same function with the "reflective" option and we load "apply.kif" and call "apply".

Given there are only 2 grammars (at the moment) these could be preloaded as we already had with the "analytic", and then the function just uses the preloaded program.

I would imagine the function would look something like this:

```scala

def analyse(text:String, grammar:String="analytic") = grammar match {
    case "analytic" => runAthanor(loadedAnalyticProgram,"apply")
    case "reflective" => runAthanor(loadedReflectiveProgram, "apply")
    case _ => Vector()
}

```

**Comment by andrewresearch** [comment]
Also, please make sure you pull and merge the latest version from GitHub, as it looks like your `build.sbt` doesn't include my latest changes.

**Comment by josephharfouch** [comment]
Hi Andrew, Ah ok, there was a misunderstanding because when I read your email I imagined that you wanted it to be a parameter given to the server as it starts, and I said I will implement it the same as the configuration of the Athanor Grammar Path. I will just figure out how to retrieve the parameter from the link rather than from the server end and submit again once I have done that. With the build.sbt I saw the conflict and did a second commit in an attempt to fix it. You are saying it is still not right? I will have a look at that one again.

**Comment by andrewresearch** [comment]
Thanks.
I couldn't see the changes in the files, but I didn't pull the branch and test locally, so perhaps I just missed the change.
I'll wait till your update, merge it in and then test it locally.

**Comment by josephharfouch** [comment]
Actually thinking about this a little bit more, I think it is going to be a real problem trying to implement it the way you are thinking even if I learn how to read parameters from the link. This is because of the inability to switch the loads around. i.e as far as I can tell once you loaded a grammar file you are stuck with it till the end of the life of the server as far as I can see. I left comments about this in AthanorInvoker as I hit this problem trying to test the feature. I will try to talk to you more about this on gitter later on the day.

**Comment by andrewresearch** [comment]
No worries, I'll take a look at this one. FYI, the endpoint is just an akka-http endpoint, so will just use the appropriate akka-http approach for the grammar parameter. 
I don't believe there should be any issue in having 2 instances of JAtanor - one for each grammar. But I'll take a look at this and get back to you.

**Pull request closed without merging**
